### Graphs and Session

- tensorflow is a declarative pragramming env
    - dataflow graph represents the computation
        - tf supports java, c++, go
    - sesssion executes the data flow

### Advantages of Dataflow

- Parallelism
- Distributed execution
- Compilation
- Portability

- Node
    - Data node
    - 
    - 

In [51]:
import tensorflow as tf

In [52]:
a = tf.random_uniform([5, 5])
b = tf.random_uniform([5, 5])
c = tf.matmul(a, b)

In [53]:
init = tf.global_variables_initializer()

In [54]:
#  Method 1:
session = tf.Session()
session.run(init)

out = session.run(c)
print(out, '\n', type(out), '\n', len(out))

session.close()

[[ 1.31543756  1.22865129  1.35703933  2.18017364  2.23766136]
 [ 1.02145875  0.71647972  0.6548577   0.95769966  1.126863  ]
 [ 1.19082963  2.05526733  1.25615788  2.15626359  2.32427835]
 [ 0.58163869  0.24022201  0.31769931  0.739115    0.81857741]
 [ 0.45718658  0.83472401  0.53333449  1.3279289   1.55229342]] 
 <class 'numpy.ndarray'> 
 5


In [55]:
# Method 2:
with tf.Session() as session:
    session.run(init)
    out = session.run(c)
    print(out, '\n', type(out), '\n', len(out))


[[ 0.85252517  1.17841733  0.83190066  1.10231376  0.41488752]
 [ 1.5291388   1.63803101  1.29957366  1.62309432  0.4828321 ]
 [ 1.08512032  1.24461472  0.76624453  1.27083194  0.31568229]
 [ 1.2388463   1.47748804  1.32231808  1.36917841  0.56449604]
 [ 0.89621842  0.98823392  0.71799749  0.96418709  0.16511238]] 
 <class 'numpy.ndarray'> 
 5


*****

### Execution Graph

In [70]:
writer = tf.summary.FileWriter('./tmp/1', session.graph)

In [57]:
x = tf.placeholder(tf.float32, [None, 5])
y = tf.placeholder(tf.float32, [5, None])
xy = tf.matmul(x, y)

In [58]:
import numpy as np

In [59]:
a = np.random.rand(3, 5)
b = np.random.rand(5, 3)
print("a:")
print(a)
print("b:")
print(b)

a:
[[ 0.73112204  0.93343925  0.81318348  0.54219148  0.24975321]
 [ 0.1541531   0.43154878  0.68637096  0.20584984  0.79464257]
 [ 0.79630278  0.62939896  0.35055138  0.2619002   0.86964   ]]
b:
[[ 0.39525646  0.92526418  0.358291  ]
 [ 0.08454691  0.16568534  0.24908032]
 [ 0.60887516  0.48663062  0.1518358 ]
 [ 0.70958797  0.73527683  0.6517879 ]
 [ 0.35413619  0.10381448  0.40417918]]


In [60]:
with tf.Session() as session:
    out = session.run(xy, feed_dict={x:a, y:b})
    print(out)

[[ 1.33620656  1.65144706  1.07226503]
 [ 0.94281065  0.78199482  0.72228611]
 [ 1.07521176  1.29451215  1.01749897]]


In [65]:
# tf.reset_default_graph()

In [66]:
W = tf.Variable(tf.random_uniform([5, 1]))
x = tf.placeholder(tf.float32, [None, 5])
b = tf.Variable(tf.random_uniform([25, 1]))
Wx = tf.matmul(x, W)
Wxb = tf.add(Wx, b)

In [67]:
x_value = np.random.rand(25,5)
print(x)

Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [69]:
init = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    out = session.run(Wx, feed_dict={x:x_value})
    print(out)

[[ 0.93331105]
 [ 1.2390213 ]
 [ 1.55630231]
 [ 1.08631551]
 [ 1.56019068]
 [ 0.87990153]
 [ 1.02167344]
 [ 1.38704801]
 [ 1.82483721]
 [ 1.28297138]
 [ 2.02176046]
 [ 1.22899103]
 [ 1.52890098]
 [ 1.62631297]
 [ 1.31277454]
 [ 1.49795651]
 [ 1.74621141]
 [ 1.28717613]
 [ 0.84472275]
 [ 1.04464257]
 [ 0.89668584]
 [ 1.6366452 ]
 [ 1.24484181]
 [ 1.53515899]
 [ 1.53715181]]
