# Let's create our first graph

In [3]:
import tensorflow as tf

In [4]:
A = tf.random_uniform([5, 5])
B = tf.random_uniform([5, 5])
C = tf.matmul(A, B)

In [5]:
init = tf.global_variables_initializer()
session = tf.Session()

session.run(init)
print(session.run(C))

session.close()

[[0.89666533 1.4180243  1.2875606  1.2395545  1.5616282 ]
 [1.5703249  1.8045712  1.3058325  1.7581294  2.0371675 ]
 [1.497572   1.8940809  1.2561579  1.5677018  1.8721936 ]
 [1.0747389  0.901188   0.7813294  0.99825114 1.0215359 ]
 [1.0249403  1.0949575  0.8678606  1.0936321  1.255387  ]]


In [6]:
init = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    print(session.run(C))


[[1.3614898  1.850666   1.6584756  2.0973797  1.5462406 ]
 [0.4766838  0.7380792  0.82513815 1.1635473  0.7530247 ]
 [0.6015756  0.92630696 0.61216617 1.341006   0.8415443 ]
 [1.088491   1.6792341  1.3512378  2.3775315  1.5857998 ]
 [1.4437666  1.7464452  1.8040991  2.1181405  1.4295472 ]]


## Let's look at the execution graph

In [7]:
tf.summary.FileWriter("./tmp/1", session.graph)

# Placeholders

In [8]:
x = tf.placeholder(tf.float32, [None, 5])
y = tf.placeholder(tf.float32, [5, None])
xy = tf.matmul(x, y)

In [9]:
import numpy as np

In [10]:
a = np.random.rand(3, 5)
b = np.random.rand(5, 6)
print("a:")
print(a)
print("b:")
print(b)

a:
[[0.37291008 0.79915346 0.09112732 0.63940248 0.44237312]
 [0.59505684 0.14401838 0.35347616 0.09390404 0.56202002]
 [0.10336104 0.8266979  0.59368679 0.96680386 0.9710561 ]]
b:
[[0.77317464 0.10787471 0.87963066 0.75745103 0.65216655 0.09055915]
 [0.86822341 0.72924638 0.9676549  0.15079365 0.38653723 0.84453986]
 [0.13376107 0.28506682 0.66589531 0.10325497 0.07614414 0.92106284]
 [0.08013564 0.02822849 0.11559255 0.09301773 0.13739791 0.08190083]
 [0.18444049 0.98475533 0.05607985 0.05523381 0.13327894 0.11422193]]


In [15]:
with tf.Session() as session:
    print(session.run(xy, feed_dict={x: a, y:b}))

[[1.127188   1.1026634  1.2607274  0.49628747 0.70585245 0.89551777]
 [0.7435887  0.8260838  0.940541   0.5487189  0.5584674  0.5729767 ]
 [1.1336643  1.766801   1.4524231  0.40781784 0.694422   1.4444603 ]]


# Variables

In [29]:
W = tf.Variable(tf.random_uniform([5, 1]))
x = tf.placeholder(tf.float32, [None, 5])

b = tf.Variable(tf.random_uniform([25,1]))
Wx = tf.matmul(x, W)
Wxb = tf.add(Wx, b)

In [30]:
x_values = np.random.rand(25, 5)
print(x_values)

[[0.17321812 0.7270183  0.58922203 0.1862764  0.49859471]
 [0.32253781 0.08973587 0.99418603 0.74272685 0.64106922]
 [0.82386116 0.31975393 0.97073773 0.29506823 0.54428934]
 [0.04801766 0.04389338 0.66021594 0.30895307 0.49097618]
 [0.97851637 0.22847965 0.85629045 0.81564883 0.95862817]
 [0.21888626 0.88886016 0.26672016 0.77116486 0.24363931]
 [0.39395744 0.95420767 0.38959937 0.71069035 0.41730178]
 [0.72933412 0.20569895 0.21550999 0.255171   0.56901763]
 [0.36235367 0.17880369 0.66400693 0.98045507 0.4989918 ]
 [0.20673421 0.89311284 0.33952817 0.06987564 0.45099962]
 [0.30465159 0.70841394 0.15898116 0.3743943  0.93902107]
 [0.8771693  0.25742267 0.509324   0.94281542 0.51611597]
 [0.09079579 0.33040835 0.6405258  0.95031594 0.84084711]
 [0.78321431 0.50869475 0.83192471 0.38745801 0.17697001]
 [0.96036064 0.27944011 0.45468268 0.39272803 0.31997539]
 [0.75852518 0.72992963 0.4903472  0.43331973 0.94178957]
 [0.10693735 0.70666786 0.67011118 0.02078229 0.5102451 ]
 [0.60014659 0

In [31]:

init = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    print(session.run(Wxb, feed_dict = {x:x_values}))

[[1.2432044]
 [1.6216048]
 [1.7469883]
 [1.3062085]
 [2.2587047]
 [1.2484851]
 [1.2298511]
 [1.2071257]
 [1.9061549]
 [1.2303988]
 [1.696307 ]
 [2.1016874]
 [2.1367154]
 [1.763719 ]
 [1.0955813]
 [1.3772529]
 [1.8155706]
 [2.3681078]
 [1.7160223]
 [1.9679455]
 [1.7235342]
 [1.0959089]
 [1.9955366]
 [1.0773177]
 [1.3445134]]
