In [2]:
import tensorflow as tf
import numpy as np

# Generate synthetic data

In [3]:
target_weight = np.array([[1, 2, 3, 4]], np.float32).transpose()
XX = np.random.rand(10000, 4)
noise = (np.random.rand(10000, 4) - 0.5) / 1000
YY = np.dot(XX + noise, target_weight)

In [19]:
print("X:")
print(XX[:5, :])
print("Y:")
print(YY.shape)

X:
[[0.92575729 0.38206382 0.88144572 0.86213619]
 [0.58663468 0.51175249 0.25049428 0.86187221]
 [0.60900929 0.44115502 0.21158051 0.53569467]
 [0.02499051 0.34189401 0.72064258 0.58264312]
 [0.69416606 0.37426029 0.8029822  0.77704349]]
Y:
(10000, 1)


# Let's build the model

In [9]:
# input data
X = tf.placeholder(tf.float32, [None, 4])
y = tf.placeholder(tf.float32, [None, 1])

# model
w = tf.Variable(tf.random_uniform([4, 1]))

# predictor algorithm
def f(X):
    return tf.matmul(X, w)

In [12]:
## Objective function
def objective(X, y):
    y_hat = f(X)
    return tf.reduce_sum(tf.square(tf.subtract(y, y_hat)))

In [16]:
step = tf.constant(1e-5)
gradient = tf.gradients(objective(X, y), [w])

with tf.Session() as session:
    init = tf.global_variables_initializer()
    session.run(init)
    
    print("Starting with a random model")
    print(session.run(w))
    
    for _ in range(500):
        # w += -step * gradient
        update_weights = tf.assign_add(w, tf.multiply(-step, gradient[0]))
        session.run(update_weights, feed_dict = {X:XX, y: YY})
    
    print("Trained Model:")
    print(session.run(w))

Starting with a random model
[[0.49668026]
 [0.44268155]
 [0.6592418 ]
 [0.14575815]]
Trained Model:
[[1.0002904]
 [2.0001597]
 [2.9999318]
 [3.999651 ]]


# Optimize our training

In [27]:
step = tf.constant(1e-4)
epochs = 1000

optimizer = tf.train.GradientDescentOptimizer(step)
train = optimizer.minimize(objective(X,y), var_list=[w])


In [28]:


with tf.Session() as session:
    # init
    session.run(tf.global_variables_initializer())
    
    print("Starting with a random weight")
    print(session.run(w))
    
    # Learning loop
    for _ in range(epochs):
        session.run(train, feed_dict={X:XX, y:YY})
        
    print("Trained Model")
    print(session.run(w))

Starting with a random weight
[[0.0032891 ]
 [0.04038525]
 [0.83338606]
 [0.15113509]]
Trained Model
[[nan]
 [nan]
 [nan]
 [nan]]
